# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formHello.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 190, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.labeHello = QtWidgets.QLabel(Form)
        self.labeHello.setGeometry(QtCore.QRect(110, 120, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labeHello.setFont(font)
        self.labeHello.setObjectName("labeHello")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FormHello"))
        self.pushButton.setText(_translate("Form", "关闭"))
        self.labeHello.setText(_translate("Form", "Hello, PyQt5"))
