# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formHello.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
pyuic编译代码分析：
1. 新生成的类的父类为object，不是我想的QWidget
2. 定义了一个方法setupUi()，其接口定义为def setupUi(self, Form)
    其中 self 是函数自己，Python 中的 self 类似于 C++语言中的 this;
    Form 是一个传入的参数，而不是在 Ui_FormHello 类里定义的一个变量
3. 前两行可知：
    所以，Form是窗体，是一个 QWidget 对象，其名称就是在 UI Designer 里设计的窗体的objectName。
    但是这个 Form不是在类 Ui_FormHello 里创建的，而是作为一个参数传入的。
4.


"""
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 190, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.labeHello = QtWidgets.QLabel(Form)
        self.labeHello.setGeometry(QtCore.QRect(110, 120, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labeHello.setFont(font)
        self.labeHello.setObjectName("labeHello")

        # 实际上，retranslateUi()函数集中设置了窗体上所有的字符串，利于实现软件的多语言界面
        self.retranslateUi(Form)
        # 最后一行语句用于窗体上各组件的信号与槽函数的自动连接
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FormHello"))
        self.pushButton.setText(_translate("Form", "关闭"))
        self.labeHello.setText(_translate("Form", "Hello, PyQt5"))
